import type { GeneratedArtifact, PluginIR, RuntimeBundle, TargetSpec } from "@hooknostic/core";

// The 1.18 loader scans `*.ts` / `*.js` only — a `.mjs` module is ignored.
const PROJECT_PLUGIN_PATH = ".opencode/plugins/hooknostic.js";

/**
 * Package delivery puts the hook module at the package root, where the entry
 * re-exports it. It is not under `.opencode/plugins/`: nothing scans a
 * package's interior, and the only module OpenCode loads is the one
 * `exports["./server"]` names.
 */
export const PACKAGE_PLUGIN_PATH = "hooknostic.js";
export const PACKAGE_ENTRY_PATH = "index.js";
export const PACKAGE_MANIFEST_PATH = "package.json";

/**
 * The entry module, and the only one OpenCode loads.
 *
 * Each re-export is conditional because either half can be absent: a config
 * needs only one of `entry` or `components`. A hooks-only package has no
 * injector, and a components-only package has no hook module — and an entry
 * importing a file the build never produced fails the *whole* plugin, taking
 * the skills and MCP servers down with it.
 */
export function packageEntrySource(options: { hooks: boolean; components: boolean }): string {
  return [
    "// Generated by hooknostic — do not edit.",
    ...(options.hooks ? [`export { HooknosticPlugin } from "./${PACKAGE_PLUGIN_PATH}";`] : []),
    ...(options.components ? [`export { default as HooknosticComponents } from "./hooknostic-agent-plugin.js";`] : []),
    "",
  ].join("\n");
}

/**
 * The npm manifest for a package with no Agent Plugins components.
 *
 * Package delivery without `components.root` reaches this path: the Agent
 * Plugin projector never runs, so nothing else would emit a manifest and the
 * output would be a bare module OpenCode cannot load. Identity comes from the
 * plugin's own IR, which is all such a build has.
 */
export function hooksOnlyManifest(plugin: PluginIR, npmName?: string): string {
  const document = {
    // The target's coordinate when it has one: an Agent Plugins name cannot be
    // scoped, so this is the only way a published package carries one.
    name: npmName ?? plugin.name,
    ...(plugin.version === undefined ? {} : { version: plugin.version }),
    ...(plugin.description === undefined ? {} : { description: plugin.description }),
    type: "module" as const,
    main: `./${PACKAGE_ENTRY_PATH}`,
    exports: { "./server": `./${PACKAGE_ENTRY_PATH}` },
    files: [PACKAGE_ENTRY_PATH, PACKAGE_PLUGIN_PATH],
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

/**
 * Generate the OpenCode hook artifacts.
 *
 * Project delivery writes a module into `.opencode/plugins/`, which OpenCode
 * scans. Package delivery emits a loadable npm package on its own — manifest
 * and entry included — because the Agent Plugin projector runs only when the
 * config declares `components.root`. When it does run it owns both files and
 * replaces these, having the package manifest's identity and knowing whether an
 * injector exists.
 */
export function generateOpenCodeArtifacts(
  plugin: PluginIR,
  target: TargetSpec,
  bundle: RuntimeBundle,
): GeneratedArtifact[] {
  if (target.delivery !== "package") return [{ path: PROJECT_PLUGIN_PATH, contents: bundle.code }];
  return [
    { path: PACKAGE_PLUGIN_PATH, contents: bundle.code },
    { path: PACKAGE_ENTRY_PATH, contents: packageEntrySource({ hooks: true, components: false }) },
    { path: PACKAGE_MANIFEST_PATH, contents: hooksOnlyManifest(plugin, target.npmName) },
  ];
}
