import { componentSummary } from "@hooknostic/agent-plugin";
import type {
  AgentPluginIssue,
  AgentPluginPackage,
  AgentPluginProjectionFile,
  AgentPluginProjectionPlan,
  AgentPluginProjector,
} from "@hooknostic/agent-plugin";
import type { TargetSpec } from "@hooknostic/core";

/**
 * OpenCode scans `.opencode/plugins/` for `*.ts` / `*.js` and does NOT recurse,
 * so package content nests safely beneath it while generated modules sit at the
 * top. Both were measured: two sibling modules each took effect, and neither
 * `plugins/sub/probe.js` nor `.opencode/other/probe.js` was loaded.
 */
const PLUGIN_DIR = ".opencode/plugins";
const INJECTOR_PATH = `${PLUGIN_DIR}/hooknostic-agent-plugin.js`;
const SKILLS_DIR = `${PLUGIN_DIR}/skills`;

/** OpenCode's local server: one argv array, and `environment` rather than `env`. */
interface OpenCodeLocalServer {
  type: "local";
  command: string[];
  environment?: Record<string, string>;
  enabled: true;
}

/** OpenCode's remote server. The client negotiates StreamableHTTP, then SSE. */
interface OpenCodeRemoteServer {
  type: "remote";
  url: string;
  headers?: Record<string, string>;
  enabled: true;
}

type OpenCodeServer = OpenCodeLocalServer | OpenCodeRemoteServer;

const PLUGIN_ROOT_PLACEHOLDER = "${PLUGIN_ROOT}";
const RUNTIME_PLUGIN_ROOT = "__HOOKNOSTIC_PLUGIN_ROOT__";

/**
 * Set the spec's `${PLUGIN_ROOT}` apart from an environment reference.
 *
 * Neither can be resolved at build time -- the install directory is not known,
 * and a secret must not be baked into a committed artifact -- so both are left
 * for the generated module. They are distinguished here because they resolve
 * from different sources at load time.
 *
 * `${VAR}` is deliberately NOT rewritten to OpenCode's `{env:VAR}` form.
 * Interpolation runs BEFORE plugin `config` hooks: in one run, the same
 * `{env:VAR}` header expanded when it came from `opencode.json` and survived
 * verbatim when a plugin injected it. A plugin therefore has to read the
 * environment itself, which is what the emitted module does.
 */
function rewriteValue(value: string): string {
  return value.replaceAll(PLUGIN_ROOT_PLACEHOLDER, RUNTIME_PLUGIN_ROOT);
}

function rewriteRecord(record: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(record).map(([key, value]) => [key, rewriteValue(value)]));
}

function translateMcp(source: AgentPluginPackage): Record<string, OpenCodeServer> {
  const servers: Record<string, OpenCodeServer> = {};
  for (const [name, server] of Object.entries(source.mcp?.mcpServers ?? {})) {
    if (server.type === "stdio") {
      servers[name] = {
        type: "local",
        // OpenCode takes one argv array, not a command plus args.
        command: [rewriteValue(server.command), ...(server.args ?? []).map(rewriteValue)],
        ...(server.env === undefined ? {} : { environment: rewriteRecord(server.env) }),
        enabled: true,
      };
    } else {
      servers[name] = {
        type: "remote",
        url: rewriteValue(server.url),
        ...(server.headers === undefined ? {} : { headers: rewriteRecord(server.headers) }),
        enabled: true,
      };
    }
  }
  return servers;
}

/**
 * Source for the module that contributes the package's components.
 *
 * OpenCode has no manifest for a project plugin, so this file IS the plugin: it
 * declares the servers and the skills directory through the `config` hook, which
 * receives the merged configuration and mutates it. `skills.paths` adds to the
 * default discovery directories rather than replacing them, and a plugin's entry
 * merges with any the project configured -- both measured.
 */
function injectorSource(
  manifest: AgentPluginPackage["manifest"],
  servers: Record<string, OpenCodeServer>,
  hasSkills: boolean,
): string {
  const identity = {
    name: manifest.name,
    ...(manifest.version === undefined ? {} : { version: manifest.version }),
    ...(manifest.description === undefined ? {} : { description: manifest.description }),
  };
  // EVERY export of a plugin module is loaded as a plugin -- a non-function
  // export fails the whole module with "Plugin export is not a function" -- so
  // the package identity is a comment rather than the named export it wants to
  // be. OpenCode has no consumer for it either way.
  return [
    "// Generated by Hooknostic from an Agent Plugins 1.0 package. Do not edit.",
    "//",
    "// Agent Plugins package identity, which OpenCode's project-plugin model has",
    "// nowhere to put:",
    ...JSON.stringify(identity, null, 2)
      .split("\n")
      .map((line) => `//   ${line}`),
    'import { fileURLToPath } from "node:url";',
    'import { dirname, join } from "node:path";',
    "",
    "// Both substitutions happen here rather than at build time: the install",
    "// directory is not known then, and a secret must not be committed. OpenCode's",
    "// own {env:} interpolation is no help -- it runs BEFORE plugin config hooks,",
    "// so a value a plugin injects is never expanded.",
    "//",
    "// The walk is structural. A JSON round-trip would corrupt a Windows plugin",
    "// root, whose backslashes are not valid JSON escapes.",
    "const pluginRoot = dirname(fileURLToPath(import.meta.url));",
    `const MARKER = ${JSON.stringify(RUNTIME_PLUGIN_ROOT)};`,
    "const resolveText = (text) =>",
    "  text",
    "    .split(MARKER)",
    "    .join(pluginRoot)",
    "    .replace(/\\$\\{([A-Za-z_][A-Za-z0-9_]*)\\}/g, (match, name) => process.env[name] ?? match);",
    "const resolve = (value) =>",
    '  typeof value === "string"',
    "    ? resolveText(value)",
    "    : Array.isArray(value)",
    "      ? value.map(resolve)",
    '      : value !== null && typeof value === "object"',
    "        ? Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolve(v)]))",
    "        : value;",
    "",
    `const mcpServers = ${JSON.stringify(servers, null, 2)};`,
    "",
    "export default async () => ({",
    "  config: (config) => {",
    ...(Object.keys(servers).length === 0
      ? []
      : [
          "    config.mcp = { ...(config.mcp ?? {}) };",
          "    for (const [name, server] of Object.entries(mcpServers)) {",
          "      config.mcp[name] = resolve(server);",
          "    }",
        ]),
    ...(hasSkills
      ? [
          "    const paths = config.skills?.paths ?? [];",
          '    const own = join(pluginRoot, "skills");',
          "    if (!paths.includes(own)) {",
          "      config.skills = { ...(config.skills ?? {}), paths: [...paths, own] };",
          "    }",
        ]
      : []),
    "  },",
    "});",
    "",
  ].join("\n");
}

/**
 * Project an Agent Plugins package into OpenCode's project-plugin layout.
 *
 * Unlike Claude and Codex this is not an installable unit: `.opencode/plugins/`
 * is read from the project directory, so the whole projection is inherently
 * project-scoped and needs no install step. The compiled hooks are already a
 * module in that directory, and this adds a second one carrying the package's
 * MCP servers and skills -- OpenCode loads every module in the directory.
 *
 * Measured on `opencode` 1.18.29 through `debug config` and `debug skill`:
 *
 * - A plugin's `config` hook mutation survives into the resolved configuration,
 *   for both `mcp` and `skills.paths`.
 * - `skills.paths` is additive: an injected path did not displace either the
 *   project's own entry or the default discovery directories.
 * - `import.meta.url` resolves to the module's real location, so a plugin can
 *   address files shipped beside it.
 * - The scan is flat: two sibling modules both loaded, while modules one level
 *   deeper and in a neighbouring directory did not.
 */
export const opencodeAgentPluginProjector: AgentPluginProjector<TargetSpec> = {
  // OpenCode reads no reverse-DNS client-extension namespace.
  namespace: "",
  // The hook module and the package share `.opencode/plugins/`.
  profiles: [
    {
      range: ">=1.10 <2",
      components: {
        "agent-plugin.manifest": {
          level: "emulated",
          rationale:
            "A project plugin is resolved by path and has no manifest, so name, version and description survive only as a comment in the generated module. They cannot be a named export: every export of a plugin module is loaded as a plugin, and a non-function one fails the whole module.",
        },
        "agent-plugin.skills": { level: "exact" },
        "agent-plugin.mcp.stdio": { level: "exact" },
        "agent-plugin.mcp.streamable-http": { level: "exact" },
        "agent-plugin.mcp.sse": {
          level: "emulated",
          rationale:
            "OpenCode declares no sse transport; a remote server is reached by the client trying StreamableHTTP and then SSE, so an sse server connects through that fall-back rather than through a declared transport.",
        },
        "agent-plugin.client-extension.files": {
          level: "unsupported",
          rationale: "OpenCode reads no portable client-extension namespace.",
        },
        "agent-plugin.runtime-package": {
          level: "unsupported",
          rationale:
            "A project plugin is loaded from disk with no install step, so a declared npm manifest and lockfile have nothing to install them.",
        },
      },
      source: {
        date: "2026-09-08",
        validatedOn: [
          {
            version: "1.18.29",
            date: "2026-09-08",
            method: "live-probe",
            artifact: ".capture/opencode-agent-plugin",
            what: "A project plugin's config hook contributed both an mcp entry and a skills.paths entry, each visible in `opencode debug config`, and the skill at the injected path was listed by `opencode debug skill`.",
          },
          {
            version: "1.18.29",
            date: "2026-09-08",
            method: "live-probe",
            artifact: ".capture/opencode-agent-plugin",
            what: "skills.paths is additive: an injected path coexisted with the project's own configured path and with the default .agents/skills discovery directory.",
          },
          {
            version: "1.18.29",
            date: "2026-09-08",
            method: "live-probe",
            artifact: ".capture/opencode-agent-plugin",
            what: "Interpolation runs BEFORE plugin config hooks: in one run the same {env:VAR} header expanded when it came from opencode.json and survived verbatim when a plugin injected it, so a plugin must read the environment itself rather than emit OpenCode's own syntax.",
          },
          {
            version: "1.18.29",
            date: "2026-09-08",
            method: "live-probe",
            artifact: ".capture/opencode-agent-plugin",
            what: "The plugin scan is flat and confined to .opencode/plugin(s): two sibling modules both loaded, while .opencode/plugins/sub/probe.js and .opencode/other/probe.js did not, so package content nests safely below the scanned directory.",
          },
          {
            version: "1.18.29",
            date: "2026-09-08",
            method: "live-probe",
            artifact: ".capture/opencode-agent-plugin",
            what: "Every export of a plugin module is loaded as a plugin: a module carrying a non-function named export beside its default failed to load entirely with \"Plugin export is not a function\".",
          },
          {
            version: "1.18.29",
            date: "2026-09-08",
            method: "type-derived",
            artifact: ".capture/opencode-agent-plugin",
            what: "A remote MCP server is attempted as [StreamableHTTP, SSE] in that order, with declared headers passed to both, which is why sse is emulated rather than unsupported.",
          },
        ],
        notes: [
          "Project plugins need no install: `.opencode/plugins/` is read from the project directory.",
          "Windows only; not probed on Linux or macOS.",
        ],
      },
    },
  ],
  project: async (source, context): Promise<AgentPluginProjectionPlan> => {
    const issues: AgentPluginIssue[] = [];
    const omissions: AgentPluginProjectionPlan["summary"]["omissions"] = [];
    const files: AgentPluginProjectionFile[] = [];
    const copiedPaths: string[] = [];

    const skillDirectories = new Set(source.skills.map((skill) => skill.directory));
    for (const file of source.files) {
      // Only the skill trees have a consumer here. The portable manifest and
      // mcp.json are replaced by the generated module, and anything else would
      // land in a directory OpenCode scans for plugin modules.
      const owner = [...skillDirectories].find(
        (directory) => file.path === directory || file.path.startsWith(`${directory}/`),
      );
      if (owner === undefined) continue;
      const path = `${SKILLS_DIR}/${file.path.slice("skills/".length)}`;
      files.push({ path, contents: file.contents, mode: file.mode });
      copiedPaths.push(path);
    }

    const servers = translateMcp(source);
    files.push({
      path: INJECTOR_PATH,
      contents: injectorSource(source.manifest, servers, source.skills.length > 0),
    });

    const copied = new Set(copiedPaths);
    for (const file of context.hookArtifacts) {
      if (copied.has(file.path) || file.path === INJECTOR_PATH) {
        issues.push({
          severity: "error",
          scope: "projection",
          path: file.path,
          message: `generated Hooknostic path ${JSON.stringify(file.path)} collides with package content`,
        });
        continue;
      }
      files.push({ ...file });
    }

    // OpenCode reads no client-extension namespace, so none is declared and the
    // component is never discovered here.
    const counts = componentSummary(source, {
      hasRuntimePackage: context.runtimePackage !== undefined,
      skipped: (component, discovered) =>
        component === "agent-plugin.runtime-package" ? discovered : 0,
    });
    if (context.runtimePackage !== undefined) {
      omissions.push({
        component: "agent-plugin.runtime-package",
        reason: "a project plugin is loaded from disk, so nothing installs its npm dependencies",
      });
    }

    return {
      files: files.sort((a, b) => a.path.localeCompare(b.path)),
      issues,
      summary: {
        components: counts,
        omissions,
        copiedPaths: [...copiedPaths].sort((a, b) => a.localeCompare(b)),
      },
    };
  },
};
