import { build } from "esbuild";
import type { RuntimeBundle } from "./adapter.js";

export interface BundleOptions {
  /** Shim entry module source (imports the user entry + adapter shim). */
  source: string;
  /** Directory used to resolve imports in the shim source. */
  resolveDir: string;
  /** Module specifier overrides (workspace/self-hosted resolution). */
  alias?: Record<string, string>;
}

/**
 * Bundle the portable runtime + user handlers + adapter shim into one
 * dependency-free ESM module, duplicated per target so every output
 * directory stays independently distributable.
 */
export async function bundleRuntime(options: BundleOptions): Promise<RuntimeBundle> {
  const result = await build({
    stdin: {
      contents: options.source,
      resolveDir: options.resolveDir,
      loader: "ts",
      sourcefile: "hooknostic-shim-entry.ts",
    },
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    write: false,
    minify: false,
    legalComments: "none",
    logLevel: "silent",
    banner: {
      js: "// Generated by hooknostic — do not edit. Source: your plugin entry + @hooknostic runtime.",
    },
    ...(options.alias ? { alias: options.alias } : {}),
  });
  const code = result.outputFiles[0]?.text;
  if (code === undefined) throw new Error("esbuild produced no runtime bundle output");
  return { code };
}
