import { build } from "esbuild";

import type { RuntimeBundle } from "./adapter.js";
import { createRequireBanner, licenseNoticesPlugin } from "./bundle-support.mjs";

export interface BundleOptions {
  /** Shim entry module source (imports the user entry + adapter shim). */
  source: string;
  /** Directory used to resolve imports in the shim source. */
  resolveDir: string;
  /** Module specifier overrides (workspace/self-hosted resolution). */
  alias?: Record<string, string>;
}

/**
 * Bundle the portable runtime + user handlers + adapter shim into one
 * dependency-free ESM module, duplicated per target so every output
 * directory stays independently distributable.
 */
export async function bundleRuntime(options: BundleOptions): Promise<RuntimeBundle> {
  const result = await build({
    stdin: {
      contents: options.source,
      resolveDir: options.resolveDir,
      loader: "ts",
      sourcefile: "hooknostic-shim-entry.ts",
    },
    // Anchor esbuild's own bookkeeping to the project, not to wherever the CLI
    // was invoked. esbuild writes every module's path into a `// <path>` banner
    // relative to absWorkingDir, which defaults to process.cwd() -- so without
    // this the emitted bytes differ between `hooknostic build` run from the
    // repo root and the same build run from the config's own directory. That
    // makes "the committed artifact matches its source" a claim about where you
    // happened to stand, and a consumer's drift check reports staleness when
    // nothing is stale.
    absWorkingDir: options.resolveDir,
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    write: false,
    outfile: "hooknostic-runtime.mjs",
    minify: false,
    legalComments: "eof",
    plugins: [licenseNoticesPlugin()],
    logLevel: "silent",
    banner: {
      js:
        "// Generated by hooknostic — do not edit. Source: your plugin entry + @hooknostic runtime.\n" +
        createRequireBanner,
    },
    ...(options.alias ? { alias: options.alias } : {}),
  });
  const code = result.outputFiles[0]?.text;
  if (code === undefined) throw new Error("esbuild produced no runtime bundle output");
  return { code };
}

/**
 * The idiomatic ESM "am I the entry module?" guard, in both orderings:
 *
 *   if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
 *   if (process.argv[1] === fileURLToPath(import.meta.url)) main();
 *
 * A *comparison* between the two is required, not mere proximity: code that
 * reads both values for unrelated reasons (logging, path construction) must
 * not be reported. The filler between operand and operator therefore excludes
 * statement punctuation (`;{}`) so a match cannot span two statements, and
 * logical operators (`&|`) so it cannot span two operands of a larger
 * expression — `process.argv[1] !== undefined && import.meta.url…` is not a
 * main-module guard.
 *
 * This stays a regex deliberately: a structural check needs a JS parser, and
 * neither esbuild (no AST access) nor anything else in this package's
 * dependency tree provides one that the published CLI could carry. The
 * diagnostic is a warning, and the residual imprecision is a contrived
 * expression that compares the two values without guarding on the result.
 */
const OPERAND_GAP = "[^;{}&|]{0,80}";
const MAIN_MODULE_GUARD = new RegExp(
  [
    `import\\.meta\\.url${OPERAND_GAP}[!=]==?${OPERAND_GAP}process\\.argv\\[1\\]`,
    `process\\.argv\\[1\\]${OPERAND_GAP}[!=]==?${OPERAND_GAP}import\\.meta\\.url`,
  ].join("|"),
);

/**
 * True when a bundled module still carries a CLI main-module guard.
 *
 * Bundling collapses the whole import graph into one file, so both sides of
 * such a guard end up naming the *generated artifact*. A guard that was
 * dormant in the source — it only fired when the module was run directly —
 * therefore becomes unconditionally true inside the artifact, and its CLI
 * body runs on every hook dispatch (typically consuming the harness's stdin
 * before the dispatcher can read the event payload).
 *
 * This only misfires in artifacts the harness *executes*
 * (`shimExecution: "command"`); one the harness imports keeps `process.argv[1]`
 * pointed at the harness's own entry, so the guard stays false.
 */
export function bundleHasMainModuleGuard(code: string): boolean {
  return MAIN_MODULE_GUARD.test(code);
}
