import { describe, expect, it } from "vitest";

import { RUNTIME_PROVIDERS, runtimeDeclarationProblem, runtimeProvider } from "./providers.js";

/** Literal `uv pip compile --generate-hashes` output, continuations and all. */
const UV_LOCKFILE = [
  "# This file was autogenerated by uv via the following command:",
  "#    uv pip compile --generate-hashes requirements.in -o requirements.txt",
  "idna==3.19 \\",
  "    --hash=sha256:5e0811a4383b21dc5838069f801c4fb62113b7447663d2530d2bd6e77b49bf15 \\",
  "    --hash=sha256:815e7be7a7806d54abb586dc943addc79e8b2ee16915059658cbeff4b1b43bf4",
  "    # via -r requirements.in",
  "",
].join("\n");

const pypi = runtimeProvider("pypi")!;

describe("the pypi provider", () => {
  it("accepts what uv actually emits", () => {
    expect(pypi.validate({ lockfile: UV_LOCKFILE })).toEqual({ ok: true });
  });

  it("refuses a requirement that is not pinned", () => {
    const result = pypi.validate({ lockfile: "idna\n" });

    expect(result.ok).toBe(false);
    expect(result.error).toContain("not pinned");
  });

  it("refuses a pinned requirement carrying no hash", () => {
    const result = pypi.validate({ lockfile: "idna==3.19\n" });

    expect(result.ok).toBe(false);
    expect(result.error).toContain("--hash");
  });

  it("refuses an editable requirement, which resolves outside the package", () => {
    const result = pypi.validate({ lockfile: "-e ./local-thing\n" });

    expect(result.ok).toBe(false);
    expect(result.error).toContain("outside the package");
  });

  it("refuses --no-binary, which would run a source distribution's setup code", () => {
    const result = pypi.validate({ lockfile: "--no-binary :all:\nidna==3.19 --hash=sha256:aa\n" });

    expect(result.ok).toBe(false);
    expect(result.error).toContain("setup code");
  });

  it("refuses a lockfile that locks nothing", () => {
    expect(pypi.validate({ lockfile: "# only a comment\n" }).ok).toBe(false);
    expect(pypi.validate({}).ok).toBe(false);
  });

  it("installs offline from the lock, wheels only", () => {
    const { command, args } = pypi.materializeCommand!({ lockfile: "req.txt", into: "out" });

    expect(command).toBe("uv");
    // --only-binary is the load-bearing one: it is this ecosystem's
    // `--ignore-scripts`, because an sdist executes setup.py at install time.
    expect(args).toContain("--only-binary=:all:");
    expect(args).toContain("--require-hashes");
    expect(args).toContain("--no-deps");
    expect(args).toEqual(expect.arrayContaining(["--target", "out", "--requirement", "req.txt"]));
  });

  it("drops the installer's own platform-native output from the tree", () => {
    // Measured: a --target install of `idna`, pure py3-none-any throughout,
    // still writes bin/idna.exe. Keeping it would make every tree non-portable.
    expect(pypi.excludedFromTree!("bin/idna.exe")).toBe(true);
    expect(pypi.excludedFromTree!("Scripts/idna.exe")).toBe(true);
    expect(pypi.excludedFromTree!(".lock")).toBe(true);
    expect(pypi.excludedFromTree!("idna/core.py")).toBe(false);
  });
});

describe("runtimeDeclarationProblem", () => {
  it("names the known ecosystems when one is not", () => {
    const problem = runtimeDeclarationProblem({ ecosystem: "composer", delivery: "author-supplied" });

    expect(problem).toContain("unknown runtime ecosystem");
    expect(problem).toContain("pypi");
  });

  it("refuses to materialize an ecosystem whose output is one platform's", () => {
    for (const ecosystem of ["cargo", "golang"]) {
      const problem = runtimeDeclarationProblem({ ecosystem, delivery: "build-materialized", into: "runtime" });

      // The rule is the same one that admits Python, applied to different bytes.
      expect(problem).toContain("does not support build-materialized");
      expect(problem).toContain("author-supplied");
    }
  });

  it("refuses npm build-materialization, which is bundling's job", () => {
    expect(runtimeDeclarationProblem({ ecosystem: "npm", delivery: "build-materialized", into: "x" })).toContain(
      "does not support build-materialized",
    );
  });

  it("requires a destination for a materialized runtime, and forbids one otherwise", () => {
    expect(runtimeDeclarationProblem({ ecosystem: "pypi", delivery: "build-materialized" })).toContain(
      'requires "into"',
    );
    expect(runtimeDeclarationProblem({ ecosystem: "pypi", delivery: "author-supplied", into: "x" })).toContain(
      "applies only to build-materialized",
    );
  });

  it("admits the shapes that are meant to work", () => {
    expect(
      runtimeDeclarationProblem({
        ecosystem: "pypi",
        delivery: "build-materialized",
        lockfile: "runtime/requirements.txt",
        into: "runtime/pypi",
      }),
    ).toBeUndefined();
    expect(
      runtimeDeclarationProblem({
        ecosystem: "npm",
        delivery: "harness-installed",
        manifest: "runtime/package.json",
        lockfile: "runtime/package-lock.json",
      }),
    ).toBeUndefined();
    expect(runtimeDeclarationProblem({ ecosystem: "cargo", delivery: "author-supplied" })).toBeUndefined();
  });
});

describe("the provider table", () => {
  it("only lets a portable ecosystem materialize at build time", () => {
    for (const provider of Object.values(RUNTIME_PROVIDERS)) {
      if (provider.portability !== "platform-specific") continue;
      expect(provider.deliveries).not.toContain("build-materialized");
    }
  });

  it("gives every ecosystem a rationale, including the ones that cannot materialize", () => {
    for (const provider of Object.values(RUNTIME_PROVIDERS)) {
      expect(provider.rationale.length).toBeGreaterThan(40);
    }
  });

  it("names its tool whenever it declares a build-time install", () => {
    for (const provider of Object.values(RUNTIME_PROVIDERS)) {
      if (!provider.deliveries.includes("build-materialized")) continue;
      expect(provider.tool).toBeTruthy();
      expect(provider.materializeCommand).toBeTypeOf("function");
    }
  });
});
