/**
 * Real-harness smoke test for Codex. Opt-in: HOOKNOSTIC_SMOKE=1 or
 * HOOKNOSTIC_SMOKE=codex. Requires the `codex` CLI on PATH and login.
 *
 * Repo-level hooks only load for *trusted* projects, so this test uses a
 * fixed project directory (`.capture/codex-smoke`) and appends a
 * `[projects] trust_level = "trusted"` entry to ~/.codex/config.toml for it
 * if missing (marked with a hooknostic comment). Hook trust itself is
 * bypassed per-invocation with --dangerously-bypass-hook-trust, since the
 * hook under test is generated by this build.
 */
import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { appendFile, mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { bundleRuntime, buildPluginIR } from "@hooknostic/core";
import { definePlugin, hook } from "@hooknostic/sdk";
import { codexShimEntrySource, codexCapabilityProfiles, generateCodexArtifacts } from "./index.js";

const smokeFlag = process.env["HOOKNOSTIC_SMOKE"] ?? "";
const enabled = smokeFlag === "1" || smokeFlag.split(",").includes("codex");

const PACKAGES = resolve(fileURLToPath(new URL(".", import.meta.url)), "../..");
const REPO = resolve(PACKAGES, "..");
const SMOKE_DIR = join(REPO, ".capture", "codex-smoke");
const ALIAS = {
  "@hooknostic/sdk": join(PACKAGES, "sdk/src/index.ts"),
  "@hooknostic/runtime": join(PACKAGES, "runtime/src/index.ts"),
  "@hooknostic/adapter-codex/shim": join(PACKAGES, "adapter-codex/src/shim.ts"),
};

const HOOKS_SOURCE = `
import { definePlugin, hook, block, replaceInput, addContext } from "@hooknostic/sdk";

export default definePlugin({
  name: "smoke",
  hooks: [
    hook("tool.before", {
      id: "smoke-guard",
      match: { kind: "shell" },
      capabilities: {
        "tool.before.block": "required",
        "tool.before.input.replace": "optional",
      },
      async run(event, ctx) {
        const { command = "" } = event.tool.input as { command?: string };
        if (command.includes("forbidden-marker")) {
          return block("hooknostic smoke: this command is blocked");
        }
        if (
          ctx.capabilities.has("tool.before.input.replace") &&
          command.includes("hooknostic-original")
        ) {
          return replaceInput({
            ...(event.tool.input as object),
            command: command.replace("hooknostic-original", "hooknostic-rewritten"),
          });
        }
      },
    }),
    hook("session.start", {
      id: "smoke-context",
      capabilities: { "session.start.context.add": "optional" },
      async run(_event, ctx) {
        if (!ctx.capabilities.has("session.start.context.add")) return;
        return addContext("hooknostic smoke token: hooknostic-context-7c4f1");
      },
    }),
  ],
});
`;

function runCommand(
  command: string,
  args: string[],
  options: { cwd: string; input?: string; timeoutMs: number },
): Promise<{ stdout: string; stderr: string; code: number | null }> {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      shell: process.platform === "win32",
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    child.stdout.setEncoding("utf8").on("data", (d: string) => (stdout += d));
    child.stderr.setEncoding("utf8").on("data", (d: string) => (stderr += d));
    const timer = setTimeout(() => {
      child.kill();
      rejectPromise(new Error(`${command} timed out\nstdout:\n${stdout}\nstderr:\n${stderr}`));
    }, options.timeoutMs);
    child.on("error", (error) => {
      clearTimeout(timer);
      rejectPromise(error);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolvePromise({ stdout, stderr, code });
    });
    if (options.input !== undefined) child.stdin.write(options.input);
    child.stdin.end();
  });
}

async function ensureProjectTrust(dir: string): Promise<void> {
  const configPath = join(homedir(), ".codex", "config.toml");
  const config = readFileSync(configPath, "utf8");
  if (config.includes(dir)) return;
  await appendFile(
    configPath,
    `\n# added by hooknostic smoke test\n[projects.'${dir}']\ntrust_level = "trusted"\n`,
    "utf8",
  );
}

describe.skipIf(!enabled)("Codex smoke (real harness)", () => {
  it(
    "block, input rewrite, and session context all function in a live session",
    { timeout: 300_000 },
    async () => {
      await rm(SMOKE_DIR, { recursive: true, force: true });
      await mkdir(SMOKE_DIR, { recursive: true });
      await runCommand("git", ["init"], { cwd: SMOKE_DIR, timeoutMs: 30_000 });
      await ensureProjectTrust(SMOKE_DIR);

      // Bundle + generate exactly as the build pipeline does.
      await writeFile(join(SMOKE_DIR, "hooks.ts"), HOOKS_SOURCE, "utf8");
      const levels = Object.fromEntries(
        Object.entries(codexCapabilityProfiles[0]!.matrix).map(([id, e]) => [id, e.level]),
      );
      const bundle = await bundleRuntime({
        source: codexShimEntrySource({
          entryImportPath: join(SMOKE_DIR, "hooks.ts").replaceAll("\\", "/"),
          capabilities: levels,
          policy: { onHookError: "continue", timeoutMs: 5000 },
          harnessVersion: "0.148.0",
        }),
        resolveDir: SMOKE_DIR,
        alias: ALIAS,
      });

      const { ir } = buildPluginIR(
        definePlugin({
          name: "smoke",
          hooks: [
            hook("tool.before", { id: "smoke-guard", async run() {} }),
            hook("session.start", { id: "smoke-context", async run() {} }),
          ],
        }),
      );
      const artifacts = generateCodexArtifacts(
        ir!,
        { id: "codex", version: ">=0.148 <1", mode: "local", output: SMOKE_DIR },
        bundle,
        {
          runtime: { onHookError: "continue", timeoutMs: 5_000, contextCharLimit: 16_000, notifyCharLimit: 2_000 },
        },
      );
      for (const artifact of artifacts) {
        const target = join(SMOKE_DIR, artifact.path);
        await mkdir(join(target, ".."), { recursive: true });
        await writeFile(target, artifact.contents, "utf8");
      }

      const prompt =
        "Do these steps in order and do not retry failures. " +
        "1. Run this exact shell command: echo hooknostic-original. Report its stdout verbatim. " +
        "2. Try to create a file named forbidden-marker.txt in the workdir using a single shell command. If the command is blocked or denied, say so and move on without retrying. " +
        "3. If your context contains a hooknostic smoke token, repeat it verbatim. Then stop.";

      const { stdout, stderr } = await runCommand(
        "codex",
        [
          "exec",
          "-",
          "-m",
          "gpt-5.3-codex-spark",
          "-s",
          "workspace-write",
          "--dangerously-bypass-hook-trust",
          "--color",
          "never",
        ],
        { cwd: SMOKE_DIR, input: prompt, timeoutMs: 280_000 },
      );

      const transcript = stdout + "\n" + stderr;
      // Input rewrite honored end-to-end.
      expect(transcript).toContain("hooknostic-rewritten");
      // Block honored: the marker file was never created.
      expect(existsSync(join(SMOKE_DIR, "forbidden-marker.txt"))).toBe(false);
      // Session context reached the model.
      expect(transcript).toContain("hooknostic-context-7c4f1");
    },
  );
});
