import { Buffer } from "node:buffer";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, expect, it, vi } from "vitest";

import { applyArtifacts, readArchive } from "./apply-renovate-artifacts.mjs";
import { buildExamples } from "./build-examples.mjs";
import {
  artifactName,
  collectManifest,
  gitBlobSha,
  outputRoots,
  planChanges,
  validateManifest,
  workflowPath,
} from "./renovate-artifacts.mjs";

const sha = "a".repeat(40);
const newer = "b".repeat(40);
const repository = "owner/project";
const file = (path, content) => ({ path, content: Buffer.from(content).toString("base64") });
const old = file(`${outputRoots[0]}/claude/runtime/hooknostic.mjs`, "old bytes");
const updated = file(old.path, "new bytes");
const added = file(`${outputRoots[1]}/codex/.codex/new.json`, "new output");
const entry = (file) => ({ path: file.path, mode: "100644", type: "blob", sha: gitBlobSha(file.content) });

function scenario(files = [updated, added]) {
  const manifest = { format: 1, headSha: sha, pr: 17, files };
  const workflow = { path: workflowPath, id: 23 };
  const run = {
    id: 42,
    workflow_id: 23,
    run_attempt: 1,
    path: workflowPath,
    event: "pull_request",
    status: "completed",
    conclusion: "success",
    head_sha: sha,
    head_branch: "renovate/npm-dependencies",
    repository: { full_name: repository },
    head_repository: { full_name: repository },
    pull_requests: [{ number: 17 }],
  };
  const pr = {
    number: 17,
    state: "open",
    user: { login: "renovate[bot]", type: "Bot" },
    head: { repo: { full_name: repository }, ref: run.head_branch, sha },
    base: { repo: { full_name: repository } },
  };
  const jobs = { total_count: 1, jobs: [{ name: "generate", status: "completed", conclusion: "success" }] };
  const tree = {
    truncated: false,
    tree: [entry(old), { path: "package.json", type: "blob", mode: "100644", sha: newer }],
  };
  const writes = [];
  let reads = 0;
  const state = { manifest, workflow, run, pr, jobs, tree, writes, beforeCommit: () => {}, onWrite: () => {} };
  state.api = vi.fn(async (path, body) => {
    if (body) {
      writes.push(body);
      state.onWrite(body);
      return { data: { createCommitOnBranch: { commit: { oid: newer } } } };
    }
    if (path.endsWith("/actions/runs/42")) return run;
    if (path.endsWith("/actions/workflows/renovate-artifacts.yml")) return workflow;
    if (path.endsWith("/jobs?per_page=100")) return jobs;
    if (path.endsWith("/artifacts?per_page=100"))
      return { total_count: 1, artifacts: [{ id: 99, name: artifactName, size_in_bytes: 500, expired: false }] };
    if (path.endsWith("/pulls/17")) {
      if (++reads === 2) state.beforeCommit();
      return pr;
    }
    if (path.endsWith(`/git/trees/${sha}?recursive=1`)) return tree;
    throw new Error(`Unexpected API request ${path}`);
  });
  state.download = vi.fn(async () => manifest);
  state.apply = () => applyArtifacts({ repository, runId: 42, attempt: 1, api: state.api, download: state.download });
  return state;
}

it("commits changed bytes and added outputs from both examples using an atomic head check", async () => {
  const s = scenario();
  expect(await s.apply()).toBe("committed example artifacts");
  expect(s.writes).toHaveLength(1);
  const input = s.writes[0].variables.input;
  expect(input.branch).toEqual({ repositoryNameWithOwner: repository, branchName: s.pr.head.ref });
  expect(input.expectedHeadOid).toBe(sha);
  expect(input.fileChanges).toEqual({
    additions: [
      { path: updated.path, contents: Buffer.from("new bytes").toString("base64") },
      { path: added.path, contents: Buffer.from("new output").toString("base64") },
    ],
    deletions: [],
  });
});

it("does not commit when every generated byte already matches", async () => {
  const s = scenario([old]);
  expect(await s.apply()).toBe("no changes");
  expect(s.writes).toEqual([]);
});

it("deletes removed outputs, including an entirely emptied output set, without touching other files", async () => {
  const s = scenario([]);
  s.tree.tree.push(entry(added));
  expect(await s.apply()).toBe("committed example artifacts");
  expect(s.writes[0].variables.input.fileChanges).toEqual({
    additions: [],
    deletions: [{ path: old.path }, { path: added.path }],
  });
});

it("skips a stale head before reading the tree", async () => {
  const s = scenario();
  s.pr.head.sha = newer;
  expect(await s.apply()).toBe("stale head or closed PR");
  expect(s.writes).toEqual([]);
  expect(s.api.mock.calls.some(([path]) => path.includes("/git/trees/"))).toBe(false);
});

it("skips a head that moves while preparing changes", async () => {
  const s = scenario();
  s.beforeCommit = () => {
    s.pr.head.sha = newer;
  };
  expect(await s.apply()).toBe("stale head or closed PR");
  expect(s.writes).toEqual([]);
});

it("treats an atomic write conflict as stale and never retries the write", async () => {
  const s = scenario();
  s.onWrite = (body) => {
    expect(body.variables.input.expectedHeadOid).toBe(sha);
    s.pr.head.sha = newer;
    throw new Error("expectedHeadOid mismatch");
  };
  expect(await s.apply()).toBe("stale head or closed PR");
  expect(s.writes).toHaveLength(1);
});

it("propagates real commit failures when the head has not changed", async () => {
  const s = scenario();
  s.onWrite = () => {
    throw new Error("credential rejected");
  };
  await expect(s.apply()).rejects.toThrow("credential rejected");
});

it("skips superseded run attempts and closed PRs", async () => {
  const s = scenario();
  s.run.run_attempt = 2;
  expect(await s.apply()).toBe("stale attempt");
  expect(s.download).not.toHaveBeenCalled();
  s.run.run_attempt = 1;
  s.pr.state = "closed";
  expect(await s.apply()).toBe("stale head or closed PR");
  expect(s.writes).toEqual([]);
});

it("rejects foreign PRs, non-bot authors, mismatched associations, and non-Renovate branches", async () => {
  const mutations = [
    (s) => {
      s.pr.head.repo.full_name = "foreign/project";
    },
    (s) => {
      s.pr.base.repo.full_name = "foreign/project";
    },
    (s) => {
      s.pr.user.login = "human";
    },
    (s) => {
      s.pr.user.type = "User";
    },
    (s) => {
      s.pr.head.ref = "feature/update";
      s.run.head_branch = "feature/update";
    },
    (s) => {
      s.pr.head.ref = "renovate/different";
    },
    (s) => {
      s.run.pull_requests = [{ number: 18 }];
    },
    (s) => {
      s.manifest.headSha = newer;
    },
  ];
  for (const mutate of mutations) {
    const s = scenario();
    mutate(s);
    await expect(s.apply()).rejects.toThrow();
    expect(s.writes).toEqual([]);
  }
});

it("rejects wrong workflows and unsuccessful generation", async () => {
  for (const mutate of [
    (s) => {
      s.run.workflow_id = 24;
    },
    (s) => {
      s.workflow.path = ".github/workflows/foreign.yml";
    },
    (s) => {
      s.run.path = ".github/workflows/foreign.yml";
    },
    (s) => {
      s.run.event = "push";
    },
    (s) => {
      s.run.conclusion = "failure";
    },
    (s) => {
      s.run.head_repository.full_name = "foreign/project";
    },
    (s) => {
      s.jobs.jobs[0].conclusion = "failure";
    },
    (s) => {
      s.jobs.jobs[0].name = "unrelated";
    },
  ]) {
    const s = scenario();
    mutate(s);
    await expect(s.apply()).rejects.toThrow();
    expect(s.writes).toEqual([]);
  }
});

it("rejects malformed and disallowed paths before any write", async () => {
  for (const path of [
    "package.json",
    ".github/workflows/ci.yml",
    "/examples/rewrite-shell/dist/a",
    "C:/examples/rewrite-shell/dist/a",
    `${outputRoots[0]}/../package.json`,
    `${outputRoots[0]}/./a`,
    `${outputRoots[0]}//a`,
    `${outputRoots[0]}/a\\b`,
    `${outputRoots[0]}/a\nb`,
    `${outputRoots[0]}/a\0b`,
    `${outputRoots[0]}/.git/config`,
    `${outputRoots[0]}/CON`,
    `${outputRoots[0]}/a.`,
    `${outputRoots[0]}-other/a`,
  ]) {
    const s = scenario([file(path, "bad")]);
    await expect(s.apply()).rejects.toThrow("Disallowed output path");
    expect(s.writes).toEqual([]);
  }
});

it("rejects invalid content, duplicate names and file/directory collisions", () => {
  for (const files of [
    [{ ...old, content: "%%%" }],
    [old, old],
    [old, { ...old, path: old.path.toUpperCase() }],
    [old, file(`${old.path}/child`, "x")],
  ]) {
    expect(() => validateManifest({ format: 1, headSha: sha, pr: 17, files })).toThrow();
  }
});

it("refuses truncated trees, symlinks, and gitlink ancestors", () => {
  const s = scenario();
  expect(() => planChanges(s.manifest, { ...s.tree, truncated: true })).toThrow("Incomplete git tree");
  expect(() => planChanges(s.manifest, { tree: [{ ...entry(old), mode: "120000" }] })).toThrow("Non-regular");
  expect(() => planChanges(s.manifest, { tree: [{ path: "examples", type: "commit" }] })).toThrow("Non-directory");
});

const dirs = [];
afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});
it("regenerates from the root, removes stale output, and includes reports in the permitted snapshots", () => {
  const root = mkdtempSync(join(tmpdir(), "example-generation-"));
  dirs.push(root);
  for (const path of outputRoots) {
    mkdirSync(join(root, path), { recursive: true });
    writeFileSync(join(root, path, "removed.txt"), "stale");
  }
  const run = vi.fn((_command, args, options) => {
    expect(options.cwd).toBe(root);
    if (args.length === 1) return;
    const config = args.at(-1);
    const example = config.slice(0, -"/hooknostic.config.ts".length);
    mkdirSync(join(root, example, "dist"), { recursive: true });
    writeFileSync(join(root, example, "dist", "new.txt"), "new");
    writeFileSync(join(root, example, "hooknostic-build.json"), '{"digest":"new"}');
  });
  buildExamples(root, run);
  expect(run).toHaveBeenCalledTimes(5);
  expect(run.mock.calls.slice(-2).map((call) => call[1][1])).toEqual(["sync", "verify"]);
  const snapshot = collectManifest(root, sha, 17);
  for (const path of outputRoots) {
    expect(snapshot.files).toContainEqual(file(`${path}/hooknostic-build.json`, '{"digest":"new"}'));
    expect(snapshot.files.some((item) => item.path === `${path}/removed.txt`)).toBe(false);
    expect(existsSync(join(root, path, "..", "hooknostic-build.json"))).toBe(false);
  }
});
it("collects hidden outputs and observes deletions on the next snapshot", () => {
  const root = mkdtempSync(join(tmpdir(), "artifact-manifest-"));
  dirs.push(root);
  for (const dir of outputRoots) mkdirSync(join(root, dir), { recursive: true });
  const path = `${outputRoots[1]}/.hidden.json`;
  writeFileSync(join(root, path), "bytes");
  expect(collectManifest(root, sha, 17).files).toEqual([file(path, "bytes")]);
  rmSync(join(root, path));
  expect(collectManifest(root, sha, 17).files).toEqual([]);
});

it.skipIf(process.platform === "win32")("rejects symlink outputs in the producing job", () => {
  const root = mkdtempSync(join(tmpdir(), "artifact-symlink-"));
  dirs.push(root);
  for (const dir of outputRoots) mkdirSync(join(root, dir), { recursive: true });
  symlinkSync("/etc/passwd", join(root, outputRoots[0], "link"));
  expect(() => collectManifest(root, sha, 17)).toThrow("regular file");
});

// The apply workflow runs on Linux; Python only parses the ZIP container.
it.skipIf(process.platform === "win32")("reads exactly one JSON member without extracting archive paths", () => {
  const zip = (names) =>
    execFileSync("python3", [
      "-c",
      `
import io, json, sys, zipfile
output = io.BytesIO()
with zipfile.ZipFile(output, 'w') as archive:
    for name in json.loads(sys.argv[1]): archive.writestr(name, '{"ok":true}')
sys.stdout.buffer.write(output.getvalue())
`,
      JSON.stringify(names),
    ]);
  expect(readArchive(zip(["manifest.json"]))).toEqual({ ok: true });
  for (const names of [["../manifest.json"], ["manifest.json", "code.js"], ["manifest.json", "manifest.json"]]) {
    expect(() => readArchive(zip(names))).toThrow();
  }
});

it("keeps the generating job unprivileged and the applying job on default-branch code", () => {
  const read = (name) => readFileSync(new URL(`../.github/workflows/${name}`, import.meta.url), "utf8");
  const generate = read("renovate-artifacts.yml");
  const apply = read("renovate-artifacts-apply.yml");
  expect(generate).toContain("contents: read");
  expect(generate).not.toMatch(/secrets\.|: write|pull_request_target/);
  expect(generate).toContain("persist-credentials: false");
  expect(generate).toContain("run: pnpm build:examples");
  expect(apply).toContain("workflow_run:");
  expect(apply).toContain("ref: ${{ github.sha }}");
  expect(apply).toContain("persist-credentials: false");
  expect(apply).toContain("secrets.RENOVATE_ARTIFACTS_TOKEN");
  expect(apply).not.toMatch(/pnpm install|pnpm build|pull_request_target/);
});
